# Generated by Django 2.1.5 on 2019-01-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lang', models.CharField(help_text='Enter The language. (e.g. Spanish, English)', max_length=200)),
            ],
        ),
    ]
